### ISSUE TITLE
Anmeldung via Spracherkennung

### ISSUE THREAD

**Issue by 0xalwayslucky** [deep-green/deep-green#12]
- [ ] Anmeldung mit Gastkonto

- [ ] Anmeldung über Ansagen der Daten

- [ ] Anmeldung via Stimmerkennung

- [ ] Anmeldung mit TAN via E-Mail

**Comment by lilalunex** [comment]
Zum 18.05, über Google Home

- System Architektur Diagramm
- Hello World mit Google Home / Android
- Code über .js realisierbar

Anmeldung über Voice Assistant:
- wird nicht eingesetzt
- Stimmerkennung: Alexa: kann deine Stimme speichern und als Passwort benutzen (?)
- TAN: umständlich
- Buchstaben ansagen: Nicht möglich durch Intents (?) / einzelne Buchstaben ungenau für Google
- Gastkonto: möglich
