### ISSUE TITLE
Datenbank

### ISSUE THREAD

**Issue by lilalunex** [deep-green/deep-green#19]
- [x] Template
    - [x] Template

**Comment by reinkepatrick** [comment]
| **field**| **datatype** | **Anmerkung**   |
|:---------|:----------:|:-------------------|
| _id        | ObjectID | primary key |
| username | String |  |
| password | String |  |
| elo | int32 | Initialwert: 1000 (?) |
| token | JWT-Token (String) | |

**Comment by lilalunex** [comment]
@reinkepatrick done
