### ISSUE TITLE
Ausbesserungen

### ISSUE THREAD

**Issue by reinkepatrick** [deep-green/deep-green#8]
# Mockup
## Logout Button
- [x] Logout Button im Hauptmenü einfügen

## Bilderkennung
- [x] Übersicht von der Bilderkennung
- [x] Änderung der Bilderkennung nachdem hochladen

## Speicherstände
- [x] Spielstände umbenennen können
- [ ] Automatisches abspeichern
- [x] Anzeige der letzten 10 Spiele
- [ ] Endgültiges speichern von Spielen

## Historie 
- [ ] KI Gegner -> Historie Interaktiv verwendbar
- [ ] Echte Gegner -> Nur Ansicht
- [ ] Spielzüge markieren

## Entfernungen
- [x] Brief-Spielmodus komplett

## Spielbrett
- [x] Figuren tauschen Button hinzufügen

# User Stories
- [ ] Timer für Spiele gegen echte Spieler

# Einladung 
- [ ] Hinweis oder Spielbrett anzeige beim einladen in ein geladenes Spiel

# Use Case
## Im Spiel (ohne Sprachsteuerung)
- [x] Benutzer zu Spieler ändern
- [x] Spielzug rückgängig machen nur bei KI

## Sprachsteuerung
- [x] Trennung der Diagramme (Im Spiel & Hauptmenü)

# Matchmaking
- [ ] ELO System

# Glossar 
- [x] Benutzer - Komma entfernen

**Comment by NicolaKuehnert** [comment]
## Mockups
Ich habe die Mockups jetzt durch nummeriert. Die kommenden Nummern beziehen sich auf eben jene Nummerierung.
* 1.2 hat nun einen __Logout Button__
* 2.4 hat nun noch eine Box für Schachfiguren. Nach dem Auswählen des Bildes soll das erkannte Schachbrett direkt __angezeigt__ werden und es kann __ausgebessert__ werden
* 3 zeigt nun 10 Spielstände und keine Brief Spiele mehr
    * Automatisches Speichern lässt sich nicht in Mockups darstellen, falls doch Ideen vorhanden sind, immer raus damit
    * 3 hat ebenfalls ein paar "Umbenannte Spielstände" 
        * 3.3 zeigt die Eingabe des neuen Namens
* Die Auswahl zwischen "Brief Modus" und "Schnelles Spiel" wurde vollständig entfernt
* 4.2 hat nun einen "Auswählen" Button, zum Figuren tauschen
